[2022-01-25 19:01:04,937] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.extract_all_dataa manual__2022-01-25T19:01:02.594300+00:00 [queued]>
[2022-01-25 19:01:04,949] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ingest_data.extract_all_dataa manual__2022-01-25T19:01:02.594300+00:00 [queued]>
[2022-01-25 19:01:04,949] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 19:01:04,949] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-25 19:01:04,949] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-25 19:01:04,959] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): extract_all_dataa> on 2022-01-25 19:01:02.594300+00:00
[2022-01-25 19:01:04,963] {standard_task_runner.py:52} INFO - Started process 1890 to run task
[2022-01-25 19:01:04,966] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ingest_data', 'extract_all_dataa', 'manual__2022-01-25T19:01:02.594300+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dag_01.py', '--cfg-path', '/tmp/tmpuie4nsq5', '--error-file', '/tmp/tmpwj5_wzvn']
[2022-01-25 19:01:04,967] {standard_task_runner.py:77} INFO - Job 26: Subtask extract_all_dataa
[2022-01-25 19:01:05,022] {logging_mixin.py:109} INFO - Running <TaskInstance: ingest_data.extract_all_dataa manual__2022-01-25T19:01:02.594300+00:00 [running]> on host 223810fcea28
[2022-01-25 19:01:05,068] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ingest_data
AIRFLOW_CTX_TASK_ID=extract_all_dataa
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T19:01:02.594300+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-25T19:01:02.594300+00:00
[2022-01-25 19:01:05,069] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-25 19:01:05,070] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/functions/extract.py']
[2022-01-25 19:01:05,081] {subprocess.py:85} INFO - Output:
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO - --------------------- EMPIEZA ---------------------------
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO - /tmp/***tmpt91nmiyq
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO - Traceback (most recent call last):
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO -   File "/opt/***/dags/functions/extract.py", line 8, in <module>
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO -     from settings import AV_STORIC_API
[2022-01-25 19:01:06,003] {subprocess.py:89} INFO - ModuleNotFoundError: No module named 'settings'
[2022-01-25 19:01:06,066] {subprocess.py:93} INFO - Command exited with return code 1
[2022-01-25 19:01:06,084] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-01-25 19:01:06,091] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=ingest_data, task_id=extract_all_dataa, execution_date=20220125T190102, start_date=20220125T190104, end_date=20220125T190106
[2022-01-25 19:01:06,106] {standard_task_runner.py:92} ERROR - Failed to execute job 26 for task extract_all_dataa
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-01-25 19:01:06,152] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-25 19:01:06,182] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
